@endpoint = https://6f9de01324.execute-api.eu-west-3.amazonaws.com/prod/

GET {{endpoint}}/hello/
###


GET {{endpoint}}/talents?talentId=333222rre
###

GET {{endpoint}}/talents?location=London
###

POST {{endpoint}}/talents/
Content-Type: application/json

{
    "location": "London",
    "name": "Chun Li"
}
###