@endpoint = https://weou01d8mi.execute-api.eu-west-2.amazonaws.com/prod/

GET {{endpoint}}/hello/
###


GET {{endpoint}}/talents?talentId=333222rre
###

POST {{endpoint}}/talents/
Content-Type: application/json

{
    "location": "London",
    "name": "Chun Li"
}
###